### ISSUE TITLE
RuntimeError: Failed to add edge detection

### ISSUE THREAD

**Issue by JonathanGSL** [pimoroni/weatherhat-python#28]
This code:

```
import weatherhat
import time

sensor = weatherhat.WeatherHAT()

while True:
        sensor.update(interval = 0.5)
        time.sleep(1.0)

```

...produces this error:
```
Traceback (most recent call last):
  File "/home/pi/go.py", line 4, in <module>
    sensor = weatherhat.WeatherHAT()
             ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pi/.local/lib/python3.11/site-packages/weatherhat/__init__.py", line 80, in __init__
    self._ioe.on_interrupt(self.handle_ioe_interrupt)
  File "/home/pi/.local/lib/python3.11/site-packages/ioexpander/__init__.py", line 411, in on_interrupt
    self._gpio.add_event_detect(self._interrupt_pin, self._gpio.FALLING, callback=callback, bouncetime=1)
RuntimeError: Failed to add edge detection

```

Fresh install of latest Rasbian (no desktop) on Pi 4.

Any help gratefully received.

**Comment by Gadgetoid** [comment]
This usually means the interrupt pin is in use by some other process or feature. Make sure 1-wire, for example, is not enabled in `/boot/firmware/config.txt` (or Raspberry Pi configuration interfaces menu) since that uses GPIO 4 by default.

Note: if you're feeling brave, it would be useful if you tried the code here: https://github.com/pimoroni/weatherhat-python/pull/29

**Comment by JonathanGSL** [comment]
Away at the moment but will try when I get home. Thanks so much for an excellent, supporting response!

**Comment by Gadgetoid** [comment]
Since the port to Pi 5 / gpiod this code is no longer present, so hopefully it works/still works for you with the new v1.0.0 version!
